rm OH counties from disabled vaccinations
covid-projections/covid-projections pull request #2576
Opened 2021-01-28 18:37 UTC by TomGoBravo

For https://trello.com/c/J3M0Ksb5/827-unmask-ohio-vaccination-data this undoes
https://github.com/covid-projections/covid-projections/pull/2499﻿

2021-01-28 18:38 UTC, TomGoBravo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Unmask Ohio vaccination data](https://trello.com/c/J3M0Ksb5/827-unmask-ohio-vaccination-data)

2021-01-28 20:56 UTC, mikelehen approved these changes
woot!  Thanks for handling.

2021-01-28 20:58 UTC, mikelehen requested changes
Actually, looks like we have no 2nd shot data and that's causing weird things...

![image](https://user-images.githubusercontent.com/206364/106198127-7efdfe00-6168-11eb-9e26-111653980929.png)

2021-01-29 01:24 UTC, pnavarrc commented
I think `develop` has data for Ohio now, so rebasing might solve this issue. I also pushed the branch `pablo/vaccines-chart-nan-handling` to handle that case, in case you want to grab the code cc @TomGoBravo @mikelehen

2021-02-03 18:31 UTC, TomGoBravo commented
Looks like OH sorted out their county level dashboard: https://covid-projections-kusendsdw.vercel.app/us/ohio-oh/county/union_county/chart/6?s=1574514
I suspect there are still problems in the FE code with rendering a timeseries of all zeros https://trello.com/c/gmpQgViy/859-oh-vaccine-timeseries-rendering-mixup and something with a null causes a problem https://trello.com/c/AOTJHEU7/857-fix-handling-of-nulls-on-frontend-for-vaccination-data
@mikelehen

2021-02-03 19:17 UTC, mikelehen approved these changes
Awesome! Thanks for keeping tabs on this.

2021-02-03 19:39 UTC, merged