handle failure to write to localStorage more gracefully
covid-projections/covid-projections pull request #2714
Opened 2021-02-11 01:43 UTC by pnavarrc

2021-02-11 02:48 UTC, mikelehen requested changes
I think we need to do a bit more to ensure localStorage is really available.

2021-02-11 02:48 UTC, mikelehen commented on src/common/fullstory.ts
>      return;
I think just referencing `localStorage` can throw an exception.  In fact, it's the above line that is showing up in sentry.  https://sentry.io/organizations/covidactnow/issues/2188103312/?project=5444052&referrer=slack

The recommended way to detect if storage is available is here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#testing_for_availability

2021-02-11 21:14 UTC, mikelehen approved these changes

2021-02-11 21:14 UTC, mikelehen commented on src/common/fullstory.ts
> +      storage.length !== 0
FWIW- We could probably treat "quota exceeded" as if storage isn't available and just replace this whole catch block with `return false;`.  But probably (hopefully) won't come up in practice.

2021-02-11 23:37 UTC, merged

2021-02-12 01:01 UTC, pnavarrc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Render Website with All Cookies Turned Off](https://trello.com/c/Ww0n90tS/907-render-website-with-all-cookies-turned-off)